version: '3.8'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: e-obrazovanje
  
  adminer:
    image: adminer
    depends_on: 
      - postgres-db
    ports:
      - 8080:8080