insert into authority (id, role) values (1,'ROLE_STUDENT'), (2,'ROLE_TEACHER'), (3,'ROLE_ADMIN');

insert into users (user_type,first_name,last_name,username,password,enabled,index_number)
values
('student','Marko','Markovic','mare021','$2a$10$kMLJl/fG/j6OHIPLKUC8fetWtt1cXv8fgJTOpOLRSQcotxsmyCDJy',TRUE, 'R2-123-2021'), -- sifra 123, id 1
('student','Petar','Petrovic','pero','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-456-2021'),    -- id 2
('student','Nadja','Higl','nadja','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-654-2021'),
('student','Jelena','Arsic','jelena','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-222-2021'), 
('student','Marija','Lazovic','mara','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-111-2021'), 
('student','Veljko','Misic','veljas','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-333-2021'),
('student','Monika','Guric','monika','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-455-2021'),  
('student','Zoran','Velickovic','zoranV','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-733-2021'), 
('student','Vesna','Subicin','vesna','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-955-2021'),
('student','Ivan','Dejic','deja','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-135-2021'),
('student','Jovan','Subasic','jovan','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-364-2020'),
('student','Silvana','Tesic','silvana','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-456-2020'),
('student','Dusan','Eric','dusan','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-883-2021'),
('student','Dusan','Maric','duca','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-856-2021'), 
('student','Milena','Vesnic','mila','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-777-2021'), 
('student','Lazar','Jovanovic','lazo','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-399-2021'),  
('student','Aco','Pejovic','aca','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-315-2021'),
('student','Rada','Manojlovic','rada','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-316-2021'),  
('student','Arandjel','Zivadinovic','arandjel','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-419-2021'), 
('student','Nebojsa','Zivanovic','neso','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-221-2021'),
('student','Nikola','Obradovic','nikola','$2a$10$GQHFBBU1gG8y0W5uT7zFsO90TayiQ7ALfMlWlipIttUCKIalP0qli',TRUE, 'R2-998-2021'); 

insert into users (user_type,first_name,last_name,username,password,enabled)
values
('admin','Marta','Martic','martaa','$2a$10$GwmzvbZUxoDR.4tlCLauve7C7qKtDR1q15OcFKCGM4FcT/f5q/H1.',TRUE),      -- id 3
('teacher','Eva','Ras','eva','$2a$10$nzYuqq4AvIAH42I.f.jQDuL0247GwUFU5yF2SiSl.o5qFeU4z95DC',TRUE), 
('teacher','Elon','Musk','elon','$2a$10$nzYuqq4AvIAH42I.f.jQDuL0247GwUFU5yF2SiSl.o5qFeU4z95DC',TRUE),     
('teacher','Zoran','Djindjic','zorandj','$2a$10$nzYuqq4AvIAH42I.f.jQDuL0247GwUFU5yF2SiSl.o5qFeU4z95DC',TRUE),   
('teacher','Zivojin','Misic','zivojin','$2a$10$nzYuqq4AvIAH42I.f.jQDuL0247GwUFU5yF2SiSl.o5qFeU4z95DC',TRUE),   
('teacher','Nikola','Tesla','tesla','$2a$10$nzYuqq4AvIAH42I.f.jQDuL0247GwUFU5yF2SiSl.o5qFeU4z95DC',TRUE),
('teacher','Natasa','Bekvalac','natasa','$2a$10$nzYuqq4AvIAH42I.f.jQDuL0247GwUFU5yF2SiSl.o5qFeU4z95DC',TRUE), 
('teacher','Jovana','Bjelica','bjelica','$2a$10$nzYuqq4AvIAH42I.f.jQDuL0247GwUFU5yF2SiSl.o5qFeU4z95DC',TRUE),     -- id 4
('teacher','Aca','Lukas','lukas','$2a$10$nzYuqq4AvIAH42I.f.jQDuL0247GwUFU5yF2SiSl.o5qFeU4z95DC',TRUE);         -- id 5


insert into user_authority (user_id, authority_id)
values (1,1),(2,1),(3,3),(4,2),(5,2) ;

INSERT INTO "domains" ("title") VALUES
('Prvi domen'), -- id 1
('Mendix');     -- id 2

INSERT INTO "domain_problems" ("description", "title", "domain_id") VALUES
('Opis prvog domenskog problema',	'Prvi domenski problem',	1),
('Opis drugog domenskog problema',	'Drugi domenski problem',	1),
('Opis treceg domenskog problema',	'Treci domenski problem',	1),
('In this module you will learn how to switch from Mendix Studio to Mendix Studio Pro modeler to add more advanced functionalities to your app.',	'From Mendix Studio to Mendix Studio Pro',	2),
('In this module, you will explore how Mendix supports Agile methodology and enables collaboration between IT and business. This will allow you to bring value to the market quickly and to innovate.',	'Collaborating with your Team',	2),
('In this module you will learn how to use Mendix Studio to build microflows that will allow you to build custom logic to your app.',	'Add Custom Logic to your App',	2),
('In this module you will learn how to use Mendix Studio to add data in your app and structure it using the Domain Model.',	'Add Data to your App',	2),
('In this module you will learn how to add mobile-specific functionality to your app.',	'Going Mobile',	2),
('In this module you will learn how to use Mendix Studio to build an app that is user-friendly and has clear navigation.',	'Start Building your App',	2),
('In this module you will learn how to automate processes within an app by creating microflows using Mendix Studio Pro.',	'Automating Processes within an App',	2),
('In this module you will learn the importance of keeping your data safe and how you can do that in Mendix Studio Pro.',	'Securing your App',	2),
('In this module you will learn more about Mendix and where you can find all the information you need.',	'Introduction',	2),
('In this module you will learn how to use Mendix Studio Pro to make sure that the data in your database is valid and consistent.',	'Ensuring your Data is Valid and Consistent',	2);


INSERT INTO "knowledge_space_node" ("coordinate_x", "coordinate_y", "height", "width", "domain_problem_id") VALUES
(10,	10,	150,	150,	1),
(390,	10,	150,	150,	2),
(175,	160,	150,	150,	3),
(316.5,	81,	150,	150,	2),
(32.5,	234,	150,	150,	3),
(15,	50,	150,	150,	1),
(352.5,	308,	150,	150,	6),
(6.5,	150,	150,	150,	4),
(672.5,	170,	150,	150,	10),
(456.5,	56,	150,	150,	13),
(237.5,	55,	150,	150,	7),
(930.5,	291,	150,	150,	8),
(-233.5,	45,	150,	150,	9),
(-434.5,	175,	150,	150,	12),
(928.5,	76,	150,	150,	11),
(-229.5,	299,	150,	150,	5);

INSERT INTO "knowledge_spaces" ("created_at", "title", "domain_id","type") VALUES
('2021-12-13 19:17:37.075802',	'Prvi prostor znanja za prvi domen',	1,'MANUAL'),
('2021-12-13 18:17:57.696',	'iita za prvi domen',	1,'IITA'),
('2021-12-27 23:32:06.623',	'profa generisao za drugi domen',	2,'MANUAL');                                -- id 2

UPDATE "domains" SET "active_knowledge_space_id" = 2 where "id" = 1;
UPDATE "domains" SET "active_knowledge_space_id" = 3 where "id" = 2;

INSERT INTO "links" ("end_domain_problem_id", "knowledge_space_id", "start_domain_problem_id") VALUES
(3,	1,	1),
(2,	1,	3),
(1,	1,	2),
(7,	3,	8),
(9,	3,	7),
(10, 3,	11),
(12,	3,	9),
(13,	3,	14),
(8,	3,	13),
(9,	3,	10),
(15,	3,	9),
(11,	3,	8),
(16,	3,	14),
(8,	3,	16);


INSERT INTO "courses" ("description", "name", "domain_id", "teacher_id") VALUES
('Prvi kurs koji polazu polaznici, predmet kursa je prepoznavanje',	'Prvi kurs PK',	1,	4),
('This learning path will teach you how to create awesome apps using low-code.\nIf you have a business analyst focus, this is the path for you, as it focuses on both Mendix Studio and Mendix Studio pro.',	'Become a Rapid Developer',	2,	4);

INSERT INTO "courses" ("name", "identifier", "description") VALUES
('Osnove programiranja', '17 - SE0001', 'Upoznavanje studenata sa osnovnim konceptima, elementima i strukturom računarskih programa, i osnovnim algoritmima za obradu podataka.'),
('Arhitektura računara','17 - SE0014','Upoznavanje studenata sa osnovnim pojmovima računarske arhitekture, principima rada, strukturnom organizacijom računara i načinima njegove implementacije.'),
('Algebra','17 - SE0002','Osposobljavanje studenata na apstraktno mišljenje i sticanje osnovnih znanja iz oblasti elementarne, opšte, apstraktne i linearne algebre, kao i iz osnova klasične kombinatorike. Cilj predmeta je da...'),
('Sociologija tehnike','17 - E106','Osposobljenost inženjera da shvate društveni značaj i ulogu tehnike u razvoju društva, pozitine i negativne uticaje tehnike na razvoj društva i čoveka, kao i vlastiti  društveni značaj i odgovornost u stvaranju humanog društva.'),
('Web dizajn','17 - SEN006','Osposobljavanje studenata za rukovanje tehnologijama izrade web sadržaja i upoznavanje sa principima web dizajna.'),
('Internet mreže','17 - E233','Ovladavanje teorijskim osnovama i tehnologijama TCP/IP mreža.'),
('Objektno orijentisano programiranje 1','17 - SE0006','Osposobljavanje studenata za rešavanje problema iz oblasti objektno orijetnisanog programiranja.'),
('Algoritmi i strukture podataka','17 - SE0008','Upoznavanje studenata sa strukturama podataka u operativnoj memoriji i razvojem programa koji ih koriste.'),
('Matematička analiza','17 - E212S','Cilj predmeta je sticanje osnovnih znanja iz oblasti matematičke analize neophodnih za dalje izučavanje bliskih predmeta i osposobljavanje studenata za apstraktno mišljenje. Stečena znanja iz matematičke ...'),
('Objektno orijentisano programiranje 2','17 - SE1006','Upoznavanje studenata sa naprednim konceptima objektno-orijentisanog pristupa upotrebom programskog jezika Ce++ i razvojem programa istovremenom upotrebom više programerskih paradigmi ...'),
('Organizacija podataka','17 - SE0013','Osnovno obrazovanje studenata u oblasti organizacije podataka u sistemima datoteka i sistemima relacionih i nerelacionih (NoSQL) baza podataka. Ovladavanje modelima podataka i fizičkim strukturama podataka na eksternim memorijskim uređajima.'),
('Numerički algoritmi i numerički softver','17 - E231','Ovladavanje osnovnim znanjima iz numeričke analize, ovladavanje metodoologijom primene numeričkih modela u inženjerskim disciplinama, ovladavanje korišćenjem odabranog standardnog numeričkog softverskog alata.'),
('Nelinearno programiranje i evolutivni algoritmi','17 - SEAU01','Ovladavanje osnovnim principima nelinearne optimizacije (nelinearnog programiranja) i osnovnim principima evolutivnih algoritama.'),
('Diskretna matematika','17 - SE0009','Osnovni cilj predmeta jeste osposobljavanje studenata na apstraktno mišljenje i sticanje osnovnih znanja iz oblasti  klasičnih kombinatornih objekata, neklasičnih kombinatornih objekata i teorije grafova. Studenti će učiti da klasifikuju probleme...'),
('Uvod u softversko inženjerstvo','17 - SE0011','Osposobiti studente za primenu savremenih metoda, alata i najbolje prakse u procesu inženjerskog razvoja softvera. Omogućiti jasnu diferencijaciju između programiranja i softverskog inženjerstva i uloge modela životnog ciklusa softvera u procesu...'),
('Baze podataka','17 - SE0016','Osnovno obrazovanje studenata u oblasti baza podataka. Ovladavanje osnovnim pojmovima u oblasti baza podataka i osnovnim tehnikama implementacije, korišćenja i održavanja baza podataka.'),
('Operativni sistemi','17 - SE0031','Upoznavanje studenata sa pojmom operativnog sistema, njegovim osnovnim delovima i strukturom, principima rada, kao i načinima za njegovu implementaciju.'),
('Softverski obrasci i komponente','17 - SES40','Ovladavanje osnovnim teorijskim znanjima, tehnikama, alatima i preporučenom praksom iz oblasti softverskih obrazaca (Software Patterns) i razvoja softvera baziranog na komponentama (Component-Based Development – CBD). Osposobljavanje studenata za...');


INSERT INTO "tests" ("title", "course_id") VALUES
('Prvi test',	1),
('Mendix Rapid',	2);

INSERT INTO "questions" ("is_randomize", "text", "domain_problem_id", "test_id") VALUES
('0',	'Koji odgovor je tacan?',	1,	1),
('1',	'How many rows can a page have?',	9,	2),
('1',	'You would like to add 2 new attributes to an entity. The attribute A will be changed more often than viewed and the attribute B will be viewed more often than changed. How should you create the attributes A and B?',	10,	2),
('1',	'Microflows can be triggered by:',	6,	2),
('1',	'You downloaded the latest version of the project from the Team Server, and did some changes to the app. What do you need to do next for your team members to be able to view your changes?',	4,	2),
('1',	'A list view is a widget used to:',	7,	2),
('1',	'What do validation rules apply to?',	13,	2),
('0',	'You can create a part of the app functionality specifically for mobile.',	8,	2),
('1',	'The value 1.23 could be stored in an attribute of the type:',	7,	2),
('1',	'The attribute type Enumeration is used to store:',	7,	2),
('0',	'What effect does security have on the navigation of the application?',	11,	2),
('1',	'Which of the key combinations provides you with a set of available variables, functions and tokens within the expression editor?',	10,	2),
('0',	'What is the Mendix Studio?',	12,	2),
('1',	'What is a page in Mendix?',	9,	2),
('0',	'What would be the best name for a mobile-specific homepage?',	8,	2),
('1',	'Which of the following statements is true for Studio Pro and not to Studio?',	4,	2),
('1',	'A connection between two entities in Mendix is called:',	7,	2),
('0',	'A user role must have one or more module roles in every module',	11,	2),
('0',	'You can set a different homepage for mobile than for other devices.',	8,	2),
('1',	'A page is responsive when:',	9,	2),
('1',	'A critical success factor for companies working with Mendix is:',	12,	2),
('1',	'Which members of an object available in a microflow are considered to be in the scope of that microflow?',	10,	2),
('1',	'Which name should you use for an entity representing a maintenance report?',	7,	2),
('1',	'Why can you define security settings on both project and module level?',	11,	2),
('0',	'You want to share something on the App Store. You want it to be visible only by people in your company. Is this possible?',	12,	2),
('1',	'How do you add new mobile widgets to your project?',	8,	2),
('1',	'Which security level must be active to deploy an application to the test environment of a licensed node in the Mendix cloud?',	11,	2),
('1',	'What are three microflow components?',	6,	2),
('0',	'Mendix Studio Pro is a WYSIWYG editor.',	4,	2),
('1',	'When deleting a Trainee, you want all the Registrations of this Trainee to be deleted as well. What is that delete behavior called?',	13,	2),
('1',	'Which statement is true?',	10,	2),
('1',	'If a Scrum team gets stuck, because of things that are out of their control, who is responsible to remove those impediments?',	5,	2),
('1',	'When do you use in the retrieve action the option “by association”?',	10,	2),
('1',	'What would be a best practice when deleting a Location?
On delete of ‘Location’ object:',	13,	2),
('0',	'You can have different row layouts for mobile, tablet, and desktop devices.',	9,	2),
('0',	'How many default App Team roles are there?',	5,	2),
('1',	'When using the Layout Grid, what is the maximum number of horizontal columns you can create within a single area?',	9,	2),
('0',	'You can create a new app from the Mendix Developer Portal.',	5,	2),
('1',	'Where do you capture your project requirements?',	5,	2),
('0',	'It is possible to place multiple widgets in a container.',	9,	2),
('1',	'Which activity is used to change the value of an attribute?',	10,	2),
('0',	'Only users with the SCRUM Master role have access to the Team Server.',	4,	2),
('1',	'Within a given expression addDays(Date and time, Integer/Long), what do you call the ''Date and time'' parameter?',	10,	2),
('1',	'Which of the following options is a mobile-specific navigation layout?',	8,	2),
('1',	'In Mendix Studio Pro, you can access the Domain Model of your app from:',	4,	2),
('1',	'How would you implement an information entity in your domain model?',	4,	2),
('1',	'What are microflows?',	6,	2),
('1',	'Where do you configure validation rules?',	13,	2),
('1',	'How many start events can a microflow have?',	6,	2),
('1',	'When configuring an ‘Add’ button that goes to a new edit page, what must you be sure to do?',	7,	2);

INSERT INTO "answers" ("accuracy", "image_path", "is_correct", "text", "question_id") VALUES
(-100,	NULL,	'0',	'prvi',	1),
(-100,	NULL,	'0',	'drugi',	1),
(100,	NULL,	'1',	'treci',	1),
(-100,	NULL,	'0',	'1',	2),
(-100,	NULL,	'0',	'12',	2),
(-100,	NULL,	'0',	'4',	2),
(100,	NULL,	'1',	'As many as you need',	2),
(100,	NULL,	'1',	'A - calculated, B – stored',	3),
(-100,	NULL,	'0',	'Both stored',	3),
(-100,	NULL,	'0',	' A – stored, B – calculated',	3),
(-100,	NULL,	'0',	'Both calculated',	3),
(-100,	NULL,	'0',	'Widget event, Action button, Default button',	4),
(-100,	NULL,	'0',	'Entity event, Action button, Default button',	4),
(100,	NULL,	'1',	' Entity event, Action button, Widget event',	4),
(-100,	NULL,	'0',	'Default button, Navigation layout, Widget event',	4),
(100,	NULL,	'1',	' Commit your changes to the Team Server',	5),
(-100,	NULL,	'0',	'Synchronize with the Team Server',	5),
(-100,	NULL,	'0',	'Update the user story from Running to Done',	5),
(-100,	NULL,	'0',	'Publish your app to the cloud',	5),
(100,	NULL,	'1',	'Display dynamic data',	6),
(-100,	NULL,	'0',	'Display static text',	6),
(-100,	NULL,	'0',	'Change text from horizontal to vertical view',	6),
(-100,	NULL,	'0',	'Display bullet points',	6),
(100,	NULL,	'1',	'Attributes',	7),
(-100,	NULL,	'0',	'Attributes and associations',	7),
(-100,	NULL,	'0',	'Associations',	7),
(-100,	NULL,	'0',	'Entities',	7),
(100,	NULL,	'1',	'True',	8),
(-100,	NULL,	'0',	'False',	8),
(100,	NULL,	'1',	'Decimal',	9),
(-100,	NULL,	'0',	'Integer',	9),
(-100,	NULL,	'0',	'AutoNumber',	9),
(-100,	NULL,	'0',	' Long',	9),
(-100,	NULL,	'0',	' A positive or negative number',	10),
(100,	NULL,	'1',	'A list of predefined values',	10),
(-100,	NULL,	'0',	'Automatically generated positive or negative whole number',	10),
(-100,	NULL,	'0',	'A whole number that can only be positive',	10),
(-100,	NULL,	'0',	'The visibility of menu items is not affected by security',	11),
(-100,	NULL,	'0',	'With security enabled, only administrators can see menu items',	11),
(100,	NULL,	'1',	'The visibility of menu items is affected by Page and Microflow security',	11),
(-100,	NULL,	'0',	'The visibility of menu items is affected by entity security',	11),
(-100,	NULL,	'0',	'Alt+Space',	12),
(-100,	NULL,	'0',	'Tab+Space',	12),
(100,	NULL,	'1',	'Ctrl+Space',	12),
(-100,	NULL,	'0',	' Shift+Space',	12),
(-100,	NULL,	'0',	'A tool to analyze big data using advanced Business Intelligence algorithms.',	13),
(100,	NULL,	'1',	'A tool to create, develop, and deploy innovative apps at light speed.',	13),
(-100,	NULL,	'0',	'A tool where you can code your web-application using HTML.',	13),
(-100,	NULL,	'0',	' A CRM tool that offers out of the box CRM capabilities.',	13),
(-100,	NULL,	'0',	'The content of a tab container.',	14),
(100,	NULL,	'1',	'The interface to your app’s data and interaction.',	14),
(-100,	NULL,	'0',	'The HTML you have to write for the front end.',	14),
(-100,	NULL,	'0',	'A subset of a list.',	14),
(100,	NULL,	'1',	'Home_Mobile',	15),
(-100,	NULL,	'0',	'HomepageMobile',	15),
(-100,	NULL,	'0',	'Mobile_Home',	15),
(-100,	NULL,	'0',	'Homepage',	15),
(-100,	NULL,	'0',	'It has a direct link with the Developer Portal.',	16),
(100,	NULL,	'1',	'It can run off-line without Internet connection.',	16),
(-100,	NULL,	'0',	'It allows to add data to your app.',	16),
(-100,	NULL,	'0',	' It allows to create custom logic using microflows.',	16),
(-100,	NULL,	'0',	'An attribute',	17),
(-100,	NULL,	'0',	'A relationship',	17),
(100,	NULL,	'1',	'An association',	17),
(-100,	NULL,	'0',	' An intersection',	17),
(-100,	NULL,	'0',	'True',	18),
(100,	NULL,	'1',	'False',	18),
(-100,	NULL,	'0',	'False',	19),
(100,	NULL,	'1',	'True',	19),
(100,	NULL,	'1',	'It works and looks good on all devices',	20),
(-100,	NULL,	'0',	'It includes user interaction',	20),
(-100,	NULL,	'0',	'It rotates as you rotate your mobile',	20),
(-100,	NULL,	'0',	'It allows dynamic data to be displayed',	20),
(-100,	NULL,	'0',	'Working individually on projects depending on expertise',	21),
(100,	NULL,	'1',	'Working in small cross-functional teams',	21),
(-100,	NULL,	'0',	'Knowing object- oriented programming',	21),
(-100,	NULL,	'0',	'Implementing the waterfall project management approach',	21),
(100,	NULL,	'1',	'Attributes and associations of the entity',	22),
(-100,	NULL,	'0',	'Attributes of the entity',	22),
(-100,	NULL,	'0',	'Associations of the entity',	22),
(-100,	NULL,	'0',	'Attributes and all entities accessible via association',	22),
(-100,	NULL,	'0',	'Maintenance-Report',	23),
(100,	NULL,	'1',	'MaintenanceReport',	23),
(-100,	NULL,	'0',	'Maintenance Report',	23),
(-100,	NULL,	'0',	'Maintenance_Report',	23),
(-100,	NULL,	'0',	'It allows for a better overview.',	24),
(-100,	NULL,	'0',	'It makes the application more secure.',	24),
(-100,	NULL,	'0',	' It is a W3C standard to separate project and module security.',	24),
(100,	NULL,	'1',	' It makes it easy to reuse modules.',	24),
(-100,	NULL,	'0',	'No',	25),
(100,	NULL,	'1',	'Yes',	25),
(-100,	NULL,	'0',	' You ask the SCRUM Master to add the widget to the project',	26),
(-100,	NULL,	'0',	'The widget is automatically downloaded if you type its name in the filter field of the toolbox',	26),
(-100,	NULL,	'0',	'You download it from the Mendix homepage',	26),
(100,	NULL,	'1',	'You download them from the Marketplace',	26),
(-100,	NULL,	'0',	' Production security',	27),
(-100,	NULL,	'0',	'App Security',	27),
(-100,	NULL,	'0',	'Prototype/demo security',	27),
(100,	NULL,	'1',	'None',	27),
(-100,	NULL,	'0',	'Activity, Decision table, Parameter',	28),
(-100,	NULL,	'0',	' Activity, End event, Decision table',	28),
(-100,	NULL,	'0',	' Decision table, Exclusive merge, End event',	28),
(100,	NULL,	'1',	' Activity, End event, Parameter',	28),
(100,	NULL,	'1',	'False',	29),
(-100,	NULL,	'0',	'True',	29),
(-100,	NULL,	'0',	'Automatic delete',	30),
(-100,	NULL,	'0',	'Prevention of delete',	30),
(-100,	NULL,	'0',	' Delete associated objects',	30),
(100,	NULL,	'1',	'Cascading delete',	30),
(100,	NULL,	'1',	' Microflow expressions are used to change, check and extract data from available values.',	31),
(-100,	NULL,	'0',	'Microflow expressions are used to document the microflow actions.',	31),
(-100,	NULL,	'0',	'Microflow expressions are used to define a query to the database.',	31),
(-100,	NULL,	'0',	'Microflow expressions are used to express the flow of a microflow.',	31),
(100,	NULL,	'1',	'The Scrum Master',	32),
(-100,	NULL,	'0',	'The Project Manager',	32),
(-100,	NULL,	'0',	'The Product Owner',	32),
(-100,	NULL,	'0',	'The Development Team',	32),
(-100,	NULL,	'0',	'When you want to retrieve the association of an object.',	33),
(100,	NULL,	'1',	'When you want to retrieve the associated object from memory.',	33),
(-100,	NULL,	'0',	'Always when you want to retrieve an associated object.',	33),
(-100,	NULL,	'0',	'Only when you want to retrieve an associated list.',	33),
(100,	NULL,	'1',	'Delete ‘Location’ objects only if it is not associated with ‘TrainingEvent’ objects',	34),
(-100,	NULL,	'0',	'Keep ‘TrainingEvent’ objects',	34),
(-100,	NULL,	'0',	'Delete ‘TrainingEvent’ objects',	34),
(-100,	NULL,	'0',	'False',	35),
(100,	NULL,	'1',	'True',	35),
(-100,	NULL,	'0',	'7',	36),
(-100,	NULL,	'0',	'4',	36),
(-100,	NULL,	'0',	'6',	36),
(100,	NULL,	'1',	'5',	36),
(100,	NULL,	'1',	'12',	37),
(-100,	NULL,	'0',	'6',	37),
(-100,	NULL,	'0',	'16',	37),
(-100,	NULL,	'0',	'4',	37),
(-100,	NULL,	'0',	'False',	38),
(100,	NULL,	'1',	'True',	38),
(-100,	NULL,	'0',	' In the Stories tab in the Mendix Studio Pro.',	39),
(-100,	NULL,	'0',	' In a text document that you share with your team members.',	39),
(-100,	NULL,	'0',	'The project manager maintains a requirements document.',	39),
(100,	NULL,	'1',	' At the Stories tab underneath Collaborate in your project’s dashboard.',	39),
(100,	NULL,	'1',	'True',	40),
(-100,	NULL,	'0',	'False',	40),
(100,	NULL,	'1',	'Change object',	41),
(-100,	NULL,	'0',	'Change variable',	41),
(-100,	NULL,	'0',	'Change value',	41),
(-100,	NULL,	'0',	'Change attribute',	41),
(-100,	NULL,	'0',	'True',	42),
(100,	NULL,	'1',	'False',	42),
(-100,	NULL,	'0',	'Variable',	43),
(100,	NULL,	'1',	'Data type',	43),
(-100,	NULL,	'0',	'Token',	43),
(-100,	NULL,	'0',	'Function',	43),
(-100,	NULL,	'0',	'Popup Layout',	44),
(100,	NULL,	'1',	' Phone_Default',	44),
(-100,	NULL,	'0',	'Atlas_TopBar',	44),
(-100,	NULL,	'0',	'Atlas_Default',	44),
(-100,	NULL,	'0',	'The Connector',	45),
(-100,	NULL,	'0',	'The Domain Model tab',	45),
(100,	NULL,	'1',	'The App Explorer',	45),
(-100,	NULL,	'0',	' The Project Dashboard',	45),
(-100,	NULL,	'0',	'Replace the 1-to-many association with a many-to-many association.',	46),
(100,	NULL,	'1',	'Replace the many-to-many association with 1-to-many associations.',	46),
(-100,	NULL,	'0',	' Replace the many-to-many association with 1-to-1 associations.',	46),
(-100,	NULL,	'0',	'Replace the 1-to-many association with 1-to-1 association.',	46),
(-100,	NULL,	'0',	'Small development processes',	47),
(-100,	NULL,	'0',	' Modeled custom behavior of a default button',	47),
(100,	NULL,	'1',	' A custom logic of a Mendix application',	47),
(-100,	NULL,	'0',	'A way to describe the whole application process flow',	47),
(-100,	NULL,	'0',	'In the association properties',	48),
(-100,	NULL,	'0',	'In the validation overview of the module',	48),
(100,	NULL,	'1',	'In the entity properties',	48),
(-100,	NULL,	'0',	'At app level',	48),
(-100,	NULL,	'0',	' Unlimited',	49),
(-100,	NULL,	'0',	'This depends on the number of input parameters',	49),
(100,	NULL,	'1',	' One',	49),
(-100,	NULL,	'0',	' This depends on the trigger of the microflow',	49),
(-100,	NULL,	'0',	'Set the On-click action to Add',	50),
(100,	NULL,	'1',	' Provide entity and detailed page name',	50),
(-100,	NULL,	'0',	'Change its color',	50),
(-100,	NULL,	'0',	'Move it to the top right of the page',	50);

insert into students_courses (completed, course_id, student_id, student_index)
values
(false, 1, 1,'R2-123-2021'),
(true, 1, 2,'R2-456-2021');


